# linting
name: check-lint

on:
  workflow_call:
  workflow_dispatch:
  pull_request:

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      # check out the repo
      - uses: actions/checkout@v3

      # lint using black
      - name: set up ci tools
        run: |
          python3 -m venv bin/venv
          . bin/venv/bin/activate
          pip install -r requirements.dev.txt
          black . --check
